version: '3.9'

services:
  postgres:
    image: postgres:14
    container_name: wiki_postgres
    restart: always
    environment:
      POSTGRES_DB: wiki
      POSTGRES_USER: wiki_user
      POSTGRES_PASSWORD: wiki_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  qdrant:
    image: qdrant/qdrant
    container_name: wiki_qdrant
    restart: always
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  backend:
    build: .
    container_name: wiki_backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - qdrant
    env_file:
      - .env

volumes:
  pgdata:
  qdrant_storage:
